<?php
/**
 * @var Siteimprove_Mage_Block_Adminhtml_Overlay_Domain $this
 * @var null|string                                     $domain
 * @var null|string                                     $token
 */
$domain = $this->getDomain();
$token = $this->getToken();
?>
<script type="text/javascript">
var _si = window._si || [];
<?php if ($domain !== null): ?>
_si.push(['domain', '<?php echo $this->jsQuoteEscape($domain); ?>', '<?php echo $this->jsQuoteEscape($token) ?>']);
<?php else: ?>
_si.push(['clear']);
<?php endif; ?>
</script>
