<?php
/**
 * @var Siteimprove_Mage_Block_Adminhtml_Overlay_Input_Abstract $this
 * @var string|null                                             $url
 */
$url = $this->getInputUrl();
?>
<script type="text/javascript">
var _si = window._si || [];
<?php if ($url): ?>
_si.push(['input', '<?php
    echo $this->jsQuoteEscape($url); ?>', '<?php echo $this->jsQuoteEscape($this->getToken()) ?>']);
<?php else: ?>
_si.push(['clear']);
<?php endif; ?>
</script>
